import fs from 'node:fs';
let s=fs.readFileSync('app/page.tsx','utf8');
const replace=(from,to)=>{if(!s.includes(from))throw new Error('Missing target: '+from.slice(0,100));s=s.replace(from,to)};
replace("import { useEffect, useState } from 'react';", "import { useEffect, useRef, useState, type PointerEvent } from 'react';");
replace("import { clinic } from '@/lib/clinic';", "import { clinic } from '@/lib/clinic';\nimport { Sheet, SheetTrigger, SheetContent, SheetTitle, SheetDescription, SheetClose } from '@/components/ui/sheet';");
replace(" const [interest,setInterest]=useState('Avaliação inicial');", ` const [interest,setInterest]=useState('Avaliação inicial');
 const [scrolled,setScrolled]=useState(false),[activeSection,setActiveSection]=useState('');
 const reviewTouch=useRef<number|null>(null);
 const setFromPointer=(event:PointerEvent<HTMLDivElement>)=>{const rect=event.currentTarget.getBoundingClientRect();setComparison(Math.round(Math.max(0,Math.min(100,(event.clientX-rect.left)/rect.width*100))))};`);
const effectStart=s.indexOf(' useEffect(()=>{const items=');
const effectEnd=s.indexOf('\n return <>',effectStart);
if(effectStart<0||effectEnd<0)throw Error('effect missing');
s=s.slice(0,effectStart)+` useEffect(()=>{
   const onScroll=()=>setScrolled(window.scrollY>24);
   onScroll();window.addEventListener('scroll',onScroll,{passive:true});
   const wide=window.matchMedia('(min-width: 1025px)');
   const onResize=()=>{if(wide.matches)setMenu(false)};
   wide.addEventListener('change',onResize);
   if(!('IntersectionObserver' in window))return()=>{window.removeEventListener('scroll',onScroll);wide.removeEventListener('change',onResize)};
   const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');
   const items=document.querySelectorAll<HTMLElement>('.reveal');
   const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.remove('reveal-pending');entry.target.classList.add('revealed');revealObserver.unobserve(entry.target)}}),{threshold:0.06,rootMargin:'0px 0px -24px 0px'});
   items.forEach(el=>{if(!reduced.matches&&el.getBoundingClientRect().top>window.innerHeight)el.classList.add('reveal-pending');revealObserver.observe(el)});
   const onMotion=()=>{if(reduced.matches)items.forEach(el=>el.classList.remove('reveal-pending'))};reduced.addEventListener('change',onMotion);
   const sectionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)setActiveSection('#'+entry.target.id)}),{rootMargin:'-15% 0px -60% 0px'});
   document.querySelectorAll('main section[id]').forEach(el=>sectionObserver.observe(el));
   return()=>{window.removeEventListener('scroll',onScroll);wide.removeEventListener('change',onResize);reduced.removeEventListener('change',onMotion);revealObserver.disconnect();sectionObserver.disconnect();items.forEach(el=>el.classList.remove('reveal-pending'))};
 },[]);`+s.slice(effectEnd);
replace('<header className="header">','<header className={scrolled?"header is-scrolled":"header"}>');
replace('<nav className={menu?\'nav open\':\'nav\'} aria-label="Navegação principal">','<nav className="nav" aria-label="Navegação principal">');
replace('<a key={link} href={link} onClick={()=>setMenu(false)}>', '<a key={link} href={link} aria-current={activeSection===link?"location":undefined} onClick={()=>setMenu(false)}>');
replace('<button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label={menu?\'Fechar menu\':\'Abrir menu\'} aria-expanded={menu}>{menu?<X/>:<Menu/>}</button>',`<Sheet open={menu} onOpenChange={setMenu}><SheetTrigger className="menu-toggle" aria-label="Abrir menu"><Menu size={23}/></SheetTrigger><SheetContent className="mobile-menu" showCloseButton={false}><SheetClose className="dialog-x" aria-label="Fechar menu"><X size={22}/></SheetClose><SheetTitle className="mobile-menu-brand">sorria<span>.</span></SheetTitle><SheetDescription>Um cuidado que começa por você.</SheetDescription><nav aria-label="Navegação mobile">{[...nav,['Localização','#localizacao']].map(([label,link],i)=><a key={link} href={link} onClick={()=>setMenu(false)}><span>0{i+1}</span>{label}<ArrowUpRight size={20}/></a>)}</nav><div className="mobile-menu-bottom"><button className="button" onClick={()=>openAppointment()}><MessageCircle size={18}/> Agende sua avaliação <ArrowUpRight size={18}/></button><p>Saúde para o seu sorriso.<br/>Leveza para a sua vida.</p></div></SheetContent></Sheet>`);
replace('<h1>Seu sorriso.<br/>Sua essência.<br/><em>Nossa paixão.</em></h1>','<h1><span className="headline-line"><span>Seu sorriso.</span></span><span className="headline-line"><span>Sua essência.</span></span><span className="headline-line"><em>Nossa paixão.</em></span></h1>');
replace('<div className="hero-visual"><img','<div className="hero-visual"><div className="hero-frame"><img');
replace('fetchPriority="high"/><span className="image-caption">','fetchPriority="high"/></div><span className="image-caption">');
replace('<div className="comparison-image" role="img"', '<div className="comparison-image" onPointerDown={event=>{if(event.button!==0)return;event.currentTarget.setPointerCapture(event.pointerId);setFromPointer(event)}} onPointerMove={event=>{if(event.currentTarget.hasPointerCapture(event.pointerId))setFromPointer(event)}} onPointerUp={event=>{if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId)}} role="img"');
replace('<div className="review-controls"><button', '<div className="review-controls"><span className="review-count" aria-label={`Depoimento ${review+1} de ${reviews.length}`}>0{review+1}<i>/ 0{reviews.length}</i></span><button');
replace('<div className="reviews-grid" aria-live="polite">', '<div className="reviews-grid" aria-live="polite" onTouchStart={event=>{reviewTouch.current=event.touches[0].clientX}} onTouchEnd={event=>{if(reviewTouch.current===null)return;const delta=event.changedTouches[0].clientX-reviewTouch.current;if(Math.abs(delta)>50)setReview(current=>(current+(delta<0?1:reviews.length-1))%reviews.length);reviewTouch.current=null}} onTouchCancel={()=>{reviewTouch.current=null}}>');
replace('<article className="review-card" key={r.name}>','<article className="review-card" key={`${review}-${r.name}`}>');
fs.writeFileSync('app/page.tsx',s);
